# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ywnZ0J5XLyhRzlVlCX86KgzvDIVj7wBC
"""

import streamlit as st
import torch
import torch.nn as nn
from torchvision import transforms, models
from PIL import Image

# -------------------------------------
# Load trained model
# -------------------------------------
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
MODEL_PATH = "best_model_small.pth"    # Make sure this file is in the same folder

model = models.resnet18(weights=None)
model.fc = nn.Linear(model.fc.in_features, 1)
model.load_state_dict(torch.load(MODEL_PATH, map_location=DEVICE))
model = model.to(DEVICE)
model.eval()

# -------------------------------------
# Image preprocessing
# -------------------------------------
prep = transforms.Compose([
    transforms.Resize((32, 32)),
    transforms.ToTensor(),
])

# -------------------------------------
# Prediction function
# -------------------------------------
def predict(img):
    x = prep(img).unsqueeze(0).to(DEVICE)
    with torch.no_grad():
        prob = torch.sigmoid(model(x)).item()
    return prob

# -------------------------------------
# Streamlit UI
# -------------------------------------
st.title("AI Image Detector")
st.write("Upload an image and I'll predict whether it's **Fake** or **Real**.")

uploaded = st.file_uploader("Choose an image", type=["jpg", "jpeg", "png"])

if uploaded:
    # Load and show uploaded image
    img = Image.open(uploaded).convert("RGB")
    st.image(img, caption="Uploaded Image", use_column_width=True)

    # Get prediction
    prob_fake = predict(img)
    prob_real = 1 - prob_fake

    # Show results
    st.subheader("Prediction")
    st.write(f"**Fake Probability:** {prob_fake:.3f}")
    st.write(f"**Real Probability:** {prob_real:.3f}")

    if prob_fake > 0.5:
        st.error("This image is likely **AI-generated**.")
    else:
        st.success("This image is likely **Real**.")
